"""correct user table

Revision ID: 20c8382820f2
Revises: 22ab5a70c6f5
Create Date: 2024-11-17 16:22:13.306065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '20c8382820f2'
down_revision: Union[str, None] = '22ab5a70c6f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_followers',
    sa.Column('follower_uid', sa.Uuid(), nullable=False),
    sa.Column('followed_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['followed_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['follower_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('follower_uid', 'followed_uid')
    )
    op.drop_table('userfollow')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userfollow',
    sa.Column('user_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('followers_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['followers_uid'], ['users.uid'], name='userfollow_followers_uid_fkey'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], name='userfollow_user_uid_fkey'),
    sa.PrimaryKeyConstraint('user_uid', 'followers_uid', name='userfollow_pkey')
    )
    op.drop_table('user_followers')
    # ### end Alembic commands ###
