"""fix post table

Revision ID: 22ab5a70c6f5
Revises: e6716be7e93c
Create Date: 2024-11-15 10:24:34.741662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '22ab5a70c6f5'
down_revision: Union[str, None] = 'e6716be7e93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_uid', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'posts', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_uid')
    # ### end Alembic commands ###
