"""correct user table

Revision ID: a58e2c3f5dff
Revises: 19dd6e139438
Create Date: 2024-11-12 03:46:11.864484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'a58e2c3f5dff'
down_revision: Union[str, None] = '19dd6e139438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userfollow')
    op.drop_table('users')
    # ### end Alembic commands ###
